module Quiz.QuizData


let getQuizData() =
    [|
    "v3j>", "indent with tab 3 lines"
    "h", "go right"
    "l", "go left"
    ":s/x/y", "replace one accurance in line"
    ":s/x/y/g", "replace all x to y in line"
    ":w", "save"
    ":q", "quit"
    ":q!", "quit without saving"
    ":e f", "open file f"
    ":%s/x/y/g", "replace x by y filewide"
    ":h", "help"
    ":new", "new file"
    "ctrl-r", "redo of redo"
    "ctrl-f", "page down"
    "ctrl-b", "page up"
    "ctrl-e", "scroll line down"
    "j", "go down"
    "k", "go up"
    "x", "remove char"
    "A", "insert at the end of line"
    "dw", "delete to beginnig of next word"
    "d$", "delete to end of line"
    "de", "delete to end of current word"
    "w", "move to beginning of next word"
    "e", "move to end of cuurrent word"
    "0", "move to beginnig of the current line"
    "dd", "delete line to registry"
    "u", "redo last command"
    "U", "redo changes in current line"
    "p", "paste after cursor/on line below cursor"
    "dd3jp", "delete line, move 3 lines down, paste below current line"
    "r", "replace character under cursor"
    "ce", "replace to end of word"
    "c$", "change to end of line"
    "ctrl-g", "show file status and location"
    "G", "go to end of file"
    "gg", "go to beginnig of file"
    "/x", "search forward for x"
    "/xn", "search forward for x and again search forward for x"
    "?x", "search for x backwards"
    "ctrl-o", "go back where you was"
    "ctrl-i", "go froward where you was"
    "%", "go to matching paranthesis"
    ":4,7s/x/y/gc", "change all accurance of x to y between line 4 and 7 and ask for confirmation"
    |]
